### ISSUE TITLE
Error passing format to some filters

### ISSUE THREAD

**Issue by immortalx** [nkovacs/vue-globalize#1]
Hi, thanks for this project , it's helping me a lot.

I'm trying the date filters and when i pass anything other than the default 'medium' i get this error in console:

[vue-globalize] TypeError: vm.dateFormatter(...) is not a function

I tried in my project and running the example.

Works: {{ now | datetime('medium') }} 
Doesn't work: {{ now | datetime('long') }}

It happens with all the wrappers from Globalize.formatDate so date, datetime and time

Thank you

**Comment by nkovacs** [comment]
You have to add the formatter to the config json, otherwise it will not be generated into the bundle.
`datetime('long')` calls `Globalize.dateFormatter({ datetime: 'long' })`, so you have to add `{ "datetime": "long" }` to `"dateFormatters"` in the config json. You should also remove the ones you don't need if you're using the example's main.json.

Unfortunately, globalize's compiler is pretty limited, and wouldn't be able to find these function calls, it only works for static calls (it basically searches for `Globalize.` in your code). That's why with globalize-config-compiler you have to manually specify everything you want to use in the json.

**Comment by immortalx** [comment]
Yes, i added to main.json and it's working now. I'm new using globalize and was not aware of that configuration, thank you very much.

Unrelated to this issue but i would like to ask you if it's normal that before the page is fully loaded i can see the t function first and later it's replaced with the translation, for example it first shows t('header/post') and later replaces with translation.

That only happens in the first load.

Once again, thank you very much.

**Comment by nkovacs** [comment]
By default, the bundles for each locale are separate and loaded asynchronously, on demand, so if your browser hasn't cached the js file yet, you'll see the untranslated messages.
You have a couple options:
- You can use the sync parameter to compile everything into your main bundle if you're only using a single locale, or a few locales and you're ok with the file size of the compiled js file. See https://github.com/nkovacs/globalize-config-loader#usage.
- `$getGlobalize` returns `null` before globalize has been loaded, so you can use that to hide the content or show a loading screen instead.
- `$setLocale` returns a promise, so you can use that to delay mounting your main vm.

**Comment by immortalx** [comment]
Thank you, it worked as described.
